### ISSUE TITLE
Handle interrupt gracefully

### ISSUE THREAD

**Issue by kidonng** [deno-library/progress#10]
When the program is interruppted (for example via <kbd>ctrl</kbd> <kbd>c</kbd>), the `end()` function never gets called, neither does the `showCursor()` function. Hence, the cursor remains hidden even the program is exited.

https://github.com/deno-library/progress/blob/94710a90cde44743b179123fe190b36c15684428/multi.ts#L158-L166

**Comment by fuxingZhang** [comment]
@kidonng  can you submit a pull request ?

**Comment by fuxingZhang** [comment]
Landed in v1.3.0 

https://github.com/deno-library/progress/commit/c7f01b296bae7420215b9b256d4426bcc74660a8
