### ISSUE TITLE
Can't use it in deno tests 

### ISSUE THREAD

**Issue by bjesuiter** [deno-library/progress#13]
I want to use this in deno tests for easier visibility of long running downloads. 

However, because you check this isTTY flag, i can't use it :( 

I've disabled this check now locally for me, but it would be nice, If i could simply use your package from upstream. 

Is there any reason we might need this isTTY check especially?

**Comment by fuxingZhang** [comment]
@bjesuiter 
Landed in [v1.2.9](https://github.com/deno-library/progress/releases/tag/v1.2.9)

**Comment by fuxingZhang** [comment]
[v1.3.0](https://github.com/deno-library/progress/releases/tag/v1.3.0) is published.

changes:

1. fixed [colored string length calculation bug](https://github.com/deno-library/progress/issues/8)

2.  **Deno.consoleSize is now stable**

> [Deno v1.27.0 : Stabilize Deno.consoleSize() API](https://github.com/denoland/deno/pull/15933)

The Deno.consoleSize API change

```diff
- Deno.consoleSize(Deno.stdout.rid).columns;
+ Deno.consoleSize().columns;
```

Now you can run a wider bar without unstable.

```diff
- deno run --unstable ./examples/width.unstable.ts
+ deno run ./examples/width.ts
```

So `mod.unstable.ts` and `exmaples/width.unstable.ts` was removed.

```diff
- mod.unstable.ts
- exmaples/width.unstable.ts
```

**Comment by bjesuiter** [comment]
Thanks very much for fast reaction and merge!
