### ISSUE TITLE
Support non-linear ETA calculations

### ISSUE THREAD

**Issue by NfNitLoop** [deno-library/progress#19]
Just found this library today and am really enjoying it! Thank you!

I see that [support for ETA was recently added](https://github.com/deno-library/progress/issues/9).

But for my use case, linear ETA doesn't work very well.  I'm doing a bulk download of some data from the internet. If there's an error, I print the error and exit.  The developer (me! 😄) fixes the bug, then restarts the bulk download process. 

The download process knows how to resume.  So, say, there are 50,000 items to download, and 10,000 have been finished.  I can check the first 10k items *very fast*, and then when I get to #10001, I have to start downloading from the internet again.  So the linear calculation starts off thinking I can load each item very fast, and has a very optimistic calculation of how long the whole process will take, though loading from the internet it actually much slower than that.  So for the entire rest of the operation, the ETA is only *approaching* the correct time, never actually a good estimate.

--- 

So my request is either: 

1. (more difficult) make an option to calculate the ETA with a non-linear algorithm.  (my preference would be: according to the last X seconds of data, what is my ETA? This could be linear, just over a shorter time period.) 
1. OR:  (easier) Let users inject a function to calculate the ETA.  If they don't inject one, use the simple linear method.

Number 2 would let people play with different algorithms and submit them as PRs, so it might be less work for you? :)

**Comment by fuxingZhang** [comment]
Land on [v1.3.5](https://github.com/deno-library/progress/releases/tag/v1.3.5)

Convert `eta :eta` to `:text`, and then pass the custom ETA to ":text".

```ts
import ProgressBar from "https://deno.land/x/progress@v1.3.5/mod.ts";

const total = 100;

const progress = new ProgressBar({
  total,
  // here ==>
  display: ":bar :percent eta :eta",
  // <== here
});

let completed = 0;

function run() {
  if (completed <= total) {
    progress.render(completed++);

    setTimeout(function () {
      run();
    }, 100);
  }
}

run();

```
==>
```ts
import ProgressBar from "https://deno.land/x/progress@v1.3.5/mod.ts";

const total = 100;

const progress = new ProgressBar({
  total,
  // here ==>
  display: ":bar :percent :text",
  // <== here
});

let completed = 0;

function run() {
  if (completed <= total) {
     // here ==> Here is an example, swap out for your own algorithm
    const time = 100-completed + "s";
    // <== here
    progress.render(completed++, {
      text: "eta " + time,
    });

    setTimeout(function () {
      run();
    }, 100);
  }
}

run();
```

**Comment by NfNitLoop** [comment]
sure, but then I don't get the benefit of `prettyTimeOptions` and have to reimplement that myself. :)

**Comment by fuxingZhang** [comment]
> sure, but then I don't get the benefit of `prettyTimeOptions` and have to reimplement that myself. :)

You can import prettyTime like this:
> import { prettyTime } from "https://deno.land/x/progress@v1.3.6/time.ts";

example:

```ts
import ProgressBar from "https://deno.land/x/progress@v1.3.6/mod.ts";
// here ==>
import { prettyTime } from "https://deno.land/x/progress@v1.3.6/time.ts";
// <== here

const total = 100;

const progress = new ProgressBar({
  total,
  display: ":bar :percent :text",
});

let completed = 0;

function run() {
  if (completed <= total) {
    // here ==>
    const time = prettyTime((100-completed)*1000, {
      withSpaces: true,
      toFixedVal: 1,
      longFormat: false,
    });
    // <== here
    progress.render(completed++, {
      text: "eta " + time,
    });

    setTimeout(function () {
      run();
    }, 100);
  }
}

run();
```
