### ISSUE TITLE
MultiProgressBar misses a '\n' for the last progress bar 

### ISSUE THREAD

**Issue by bjesuiter** [deno-library/progress#23]
<img width="664" alt="Bildschirm­foto 2023-02-24 um 14 23 19" src="https://user-images.githubusercontent.com/2365676/221189440-931ab02f-a8db-483e-bb4d-08e8b8488c2c.png">

When you look at the image, you see the percent sign behind the last progress row. 
Thats my prompt sign which is on the wrong line. 

You can also see this in the following screenshots from running the MultiProgressBar in a deno test: 
<img width="870" alt="Bildschirm­foto 2023-02-24 um 14 25 38" src="https://user-images.githubusercontent.com/2365676/221189730-c67ecd70-828f-49bf-bb3c-b850d0de923f.png">

I'll add a small PR for this.

**Comment by fuxingZhang** [comment]
My test is ok.

![image](https://user-images.githubusercontent.com/25921552/221454488-96dee1fa-fb79-4850-adbb-4602d38be5d8.png)

**Comment by bjesuiter** [comment]
Hmm, I'm currently analyzing what problem there is with drawing the progress bars. 

Try to put 3 progress bars in the test. You should see that it is broken now, as it is for me. 
The third progress bar does not render while 1 &2 are, despite the data being in the array. 
also, after rendering of all three bars is complete, the next prompt will be on the same line as the 3rd progress bar, which appears in one complete rendering at the end. 

Maybe this is an issue with ANSI escape sequences used while drawing, I experimented with this on the weekend and tried to refactor it completely and it is another kind of complicated sometimes. 

I now have a solution, which is able to render 3 progress bars independently of one another from 1 readable stream for each bar, containing the completed prgress, however, 
Since my test uses fast-firing timers the rendering is sometimes a bit laggy. 

Also, printing console logs messes up the rendering of the bars, so this has to still be adjusted. 

If you're interested at looking into my refactoring, I can give you a WIP PR, if you want :)

**Comment by fuxingZhang** [comment]
Three progress bars is ok. Maybe you can try another computer
![image](https://user-images.githubusercontent.com/25921552/221770791-1b307713-d8f9-422b-9096-afa962017ec9.png)
![image](https://user-images.githubusercontent.com/25921552/221771756-3e79c919-594d-4b50-82b1-c8412fb8c172.png)
