### ISSUE TITLE
Incorrect bar size when color is used in the title

### ISSUE THREAD

**Issue by Arnaud73** [deno-library/progress#24]
Color can be used for the bar, but if being used in the title, then the bar size is shorter.

E.g.:
```
const progress = new ProgressBar({
  total: 10,
  complete: green('='),
  incomplete: yellow('-'),
  display: `:completed/:total :title [:bar] :percent`,
});
let completed = 0;

for (const file of Array.from({ length: 10 }, (value, index) => index)) {
    progress.render(completed++, {
      title: `${yellow("file")} • ${blue("en!)} → ${blue("es")}`,
    });
  }
```

If the color used in the title are removed, then the bar is displayed correctly.

**Comment by fuxingZhang** [comment]
land at [v1.3.9](https://github.com/deno-library/progress/releases/tag/v1.3.9)

**Comment by fuxingZhang** [comment]
@Arnaud73 
https://github.com/deno-library/progress/commit/25262e889f16778d2091a119829c583d82018687#diff-e8c3622ccfbed67f4b3058cd4417bf41d066236f49c6f3e63b7c243b584c6734

![image](https://github.com/deno-library/progress/assets/25921552/fae20322-2dba-4dee-8e03-60e5c131636e)

**Comment by Arnaud73** [comment]
Thanks, I just tested, and it works flawlessly!
