### ISSUE TITLE
Publish to JSR

### ISSUE THREAD

**Issue by andrewthauer** [deno-library/progress#28]
Are there any plans to publish this library to [JSR](https://jsr.io)?

**Comment by fuxingZhang** [comment]
Conflicts with Deno's import network package

![image](https://github.com/deno-library/progress/assets/25921552/39d16667-4b59-4355-8453-4a2ca3b601bb)

**Comment by fuxingZhang** [comment]
Conflicts with Deno's import network package

![image](https://github.com/deno-library/progress/assets/25921552/39d16667-4b59-4355-8453-4a2ca3b601bb)

**Comment by fuxingZhang** [comment]
done
https://jsr.io/@deno-library/progress

**Comment by andrewthauer** [comment]
Amazing. Thanks for the super fast response!
