### ISSUE TITLE
Broken with Deno 1.42.1 and std 0.221.0

### ISSUE THREAD

**Issue by jmoalves** [deno-library/progress#29]
error: Relative import path "@std/fmt/colors" not prefixed with / or ./ or ../ and not in import map from "https://deno.land/x/progress@v1.4.7/mod.ts"
    at https://deno.land/x/progress@v1.4.7/mod.ts:1:49

**Comment by jmoalves** [comment]
Version 1.4.5 works fine

**Comment by fuxingZhang** [comment]
I test is ok.

```ts
import ProgressBar from "https://deno.land/x/progress@v1.4.7/mod.ts";
import { delay } from "https://deno.land/std@0.220.1/async/delay.ts";
// or JSR
// import ProgressBar from "@deno-library/progress";
// import { delay } from "@std/async";

const total = 100;

const progress = new ProgressBar({
  total,
  complete: "=",
  incomplete: "-",
  display: ":completed/:total hello :time [:bar] :percent",
});

let completed = 0;

async function download() {
  while (completed <= total) {
    await progress.render(completed++);

    await delay(20);
  }
}

await download();
```

![image](https://github.com/deno-library/progress/assets/25921552/9fffa6d4-6e36-4e17-a958-046c3a972831)

**Comment by fuxingZhang** [comment]
Landed on [v1.4.9](https://github.com/deno-library/progress/releases/tag/v1.4.9)

The commit
> https://github.com/deno-library/progress/commit/1373e7a1af3c576dfcf7d2d791388e08472a96e8

**Comment by fuxingZhang** [comment]
Can you show me your code?

**Comment by jmoalves** [comment]
1.4.9 fixed it.
Thanks!
